# Generated by Django 5.0 on 2024-01-09 10:16

import django.db.models.functions.text
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_rating_rating_alter_rating_restaurant_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restourant',
            options={'ordering': [django.db.models.functions.text.Lower('name')]},
        ),
    ]
